### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2551' in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by srossross** [datawire/forge#102]
When ssh'ing into my machine, I get a `UnicodeEncodeError`. This does not occur when I log in locally.

```
(srossross-mac3 project1 •‿•) forge --verbose build --dry-run
Traceback (most recent call last):
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 365, in execute
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 484, in execute_pkg_resources
  File "/Users/srossross/.pex/install/Forge-0.3.18-py2-none-any.whl.b44b8bb382d77fd44fa0383179049e0f9962537c/Forge-0.3.18-py2-none-any.whl/forge/cli.py", line 515, in call_main
    exit(forge())
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/srossross/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/srossross/.pex/install/Forge-0.3.18-py2-none-any.whl.b44b8bb382d77fd44fa0383179049e0f9962537c/Forge-0.3.18-py2-none-any.whl/forge/cli.py", line 449, in build
    forge.execute(forge.build)
  File "/Users/srossross/.pex/install/Forge-0.3.18-py2-none-any.whl.b44b8bb382d77fd44fa0383179049e0f9962537c/Forge-0.3.18-py2-none-any.whl/forge/cli.py", line 332, in execute
    exe = root.run()
  File "/Users/srossross/.pex/install/Forge-0.3.18-py2-none-any.whl.b44b8bb382d77fd44fa0383179049e0f9962537c/Forge-0.3.18-py2-none-any.whl/forge/tasks.py", line 253, in run
    result.executor.echo(result.report())
  File "/Users/srossross/.pex/install/Forge-0.3.18-py2-none-any.whl.b44b8bb382d77fd44fa0383179049e0f9962537c/Forge-0.3.18-py2-none-any.whl/forge/executor.py", line 378, in echo
    print msg
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2551' in position 5: ordinal not in range(128)

```

```
(srossross-mac3 project1 ಠ_ಠ) forge build metadata
env: {GOPATH: /workspaces/personal/go, AWS_PROFILE: srossross-mfa, LOGNAME: srossross,
  USER: srossross, PROMPT_COMMAND: 'exitstatus; ', HOME: /Users/srossross, PATH: '/usr/local/sbin:/Library/Application
    Support/teradata/client/15.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/local/bin:/workspaces/personal/go/bin',
  __CF_USER_TEXT_ENCODING: '0x2D4A0905:0x0:0x0', TERM: xterm-256color, SHELL: /bin/bash,
  SHLVL: '1', KOPS_STATE_STORE: 's3://tableau-public-dev-k8s', HISTSIZE: '5000', _: /usr/local/bin/forge,
  HISTFILESIZE: '5000', P4EDITOR: vim, PYTHONPATH: ':/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
  P4CONFIG: .p4config, TMPDIR: /var/folders/5n/50k1b7cx0t32ttgy1s_k2b58pmm285/T/,
  SSH_TTY: /dev/ttys008, OLDPWD: /Users/srossross, SSH_CLIENT: 10.23.200.49 57903
    22, HISTCONTROL: 'ignoreboth:erasedups', PWD: /workspaces/tableau/project1, MAIL: /var/mail/srossross,
  SSH_CONNECTION: 10.23.200.49 57903 10.23.1.29 22}
service:
  name: project1
  profiles:
    default: {endpoint: /hello/, max_memory: 0.5G, max_cpu: 0.5}
    canary: {endpoint: /hello/, weight: 10.0, max_memory: 0.5G, max_cpu: 0.5}
  containers: [Dockerfile]
build:
  branch: master
  version: 0d8987f16d2498b8298133e7e3184ab2858eea97.sha
  profile: {endpoint: /hello/, max_memory: 0.5G, max_cpu: 0.5, name: default}
  name: project1-default
  images: {Dockerfile: '009348887430.dkr.ecr.us-west-2.amazonaws.com/project1:0d8987f16d2498b8298133e7e3184ab2858eea97.sha',
    workgroup/project1/docker-containers/frontend-container/Dockerfile: '009348887430.dkr.ecr.us-west-2.amazonaws.com/project1-workgroup-project1-docker-containers-frontend-container:0d8987f16d2498b8298133e7e3184ab2858eea97.sha'}
```

**Comment by Turee** [comment]
Any news on this?

**Comment by SimonIsMe** [comment]
```export PYTHONIOENCODING=utf8``` was helpful for me
