### ISSUE TITLE
Forge stacktrace when running forge deploy without forge.yaml

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#119]
```
plombardi@plombowski ~/w/scout> forge deploy --dry-run
Traceback (most recent call last):
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 365, in execute
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/usr/local/bin/forge/.bootstrap/_pex/pex.py", line 484, in execute_pkg_resources
  File "/home/plombardi/.pex/install/Forge-0.3.21-py2-none-any.whl.ca196217069ceef1999995a4f3185144832d8f62/Forge-0.3.21-py2-none-any.whl/forge/cli.py", line 200, in call_main
    exit(forge())
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/plombardi/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-py2.py3-none-any.whl/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/plombardi/.pex/install/Forge-0.3.21-py2-none-any.whl.ca196217069ceef1999995a4f3185144832d8f62/Forge-0.3.21-py2-none-any.whl/forge/cli.py", line 179, in deploy
    forge.execute(lambda svc: forge.deploy(*forge.build(svc)))
  File "/home/plombardi/.pex/install/Forge-0.3.21-py2-none-any.whl.ca196217069ceef1999995a4f3185144832d8f62/Forge-0.3.21-py2-none-any.whl/forge/core.py", line 294, in execute
    self.load_config()
  File "/home/plombardi/.pex/install/Forge-0.3.21-py2-none-any.whl.ca196217069ceef1999995a4f3185144832d8f62/Forge-0.3.21-py2-none-any.whl/forge/core.py", line 251, in load_config
    raise CLIError("unable to find forge.yaml, try running `forge setup`")
NameError: global name 'CLIError' is not defined
```

**Comment by plombardi89** [comment]
Looks like this might be resolved in version `forge 0.3.23`. I'll try and confirm today.
