### ISSUE TITLE
Forge installed as one user then errors out for another

### ISSUE THREAD

**Issue by pkim-auro** [datawire/forge#171]
I installed forge as the ubuntu which went in fine and works fine.

However, realizing that I should be using my own user, I installed my own profile and switched to my user.  then to test I tried just "forge" and received this:

Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 367, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 410, in _execute
  File ".bootstrap/_pex/pex.py", line 468, in execute_entry
  File ".bootstrap/_pex/pex.py", line 482, in execute_pkg_resources
  File ".bootstrap/pkg_resources/__init__.py", line 2235, in resolve
  File "/home/pkim/.pex/install/Forge-0.4.7-py2-none-any.whl.d3ef9c6c3e933bb5f7e07959f7f5e6a6322239a0/Forge-0.4.7-py2-none-any.whl/forge/cli.py", line 25, in <module>
    setup()
  File "/home/pkim/.pex/install/Forge-0.4.7-py2-none-any.whl.d3ef9c6c3e933bb5f7e07959f7f5e6a6322239a0/Forge-0.4.7-py2-none-any.whl/forge/tasks.py", line 37, in setup
    format='%(levelname)s %(task_id)s: %(message)s')
  File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/forge.log'

I'm guessing I can get around it by chown the /tmp/forge.log file but it implies that only one user would be able to execute.  I only see this as a possible problem in our control center where we manage troubleshooting.

let me know if any suggestions.

**Comment by rhs** [comment]
The log is there really mostly for debugging purposes. I can just change it to live somewhere under the user's home directory. If you work around it as you suggested for now, I can put out a fix soon.

**Comment by rhs** [comment]
I just released 0.4.8 with a fix for this. I ended up going with `/tmp/forge-<USER>-<DATE>.log`. I figure that will avoid polluting the user's home directory and older log files will be garbage collected from /tmp on typical systems.
