### ISSUE TITLE
Using Submodule in k8s with readme breaks build/deploy commands

### ISSUE THREAD

**Issue by pkim-auro** [datawire/forge#186]
v4.10

**setup:**
$REPO/k8s/deployment.yaml
$REPO/k8s/README.md
$REPO/k8s/forge-template/deployment.yaml
$REPO/k8s/forge-template/README.md

cmd: forge deploy or forge build
expected:  build or deployment
actual: error (see way below)

Other attempts: i tried to .forgeignore in the $REPO directory:
.forgeignore:
k8s/README.md
k8s/forge-template/README.md
.forge/k8s/net-diagnostics/README.md
.forge/k8s/net-diagnostics/forge-template/README.md

Specific errors in parsing were caused by lines ending in  ":" 
also lines immediately following the second # also fails.

**example:**
```
# header row
text
# second header row then next row would come up as an error
this line fails
this line also fails because of colon : somewhere in the line
## H2 header row also fails
```
**Workaround**: I was successfully able to build it after removing all # after the first block and also all : 

below error is what occurs when row 8 started with a # symbol
```
║ 72 tasks run, 1 errors
║   None: unexpected error
║
║     Traceback (most recent call last):
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/core.py", line 327, in root
║         service.go(name)
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/core.py", line 320, in service
║         goal(svc)
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/cli.py", line 180, in <lambda>
║         forge.execute(lambda svc: forge.deploy(*forge.build(svc), prune=prune))
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/core.py", line 255, in build
║         return service, self.manifest(service)
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/core.py", line 240, in manifest
║         self.kube.label(k8s_dir, labels)
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/kubernetes.py", line 161, in label
║         self._labeltate(yaml_dir, labels, annotate=False)
║       File "/home/pkim/.pex/install/Forge-0.4.10-py2-none-any.whl.0a7dd56c54e61065c2c99fd2f2d12a484674018a/Forge-0.4.10-py2-none-any.whl/forge/kubernetes.py", line 142, in _labeltate
║         for nd in compose_all(f):
║       File "/home/pkim/.pex/install/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl.b99cb007a904e5ca780f7efa316b72252aeb142a/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl/yaml/__init__.py", line 59, in compose_all
║         while loader.check_node():
║       File "/home/pkim/.pex/install/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl.b99cb007a904e5ca780f7efa316b72252aeb142a/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl/yaml/composer.py", line 18, in check_node
║         if self.check_event(StreamStartEvent):
║       File "/home/pkim/.pex/install/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl.b99cb007a904e5ca780f7efa316b72252aeb142a/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl/yaml/parser.py", line 98, in check_event
║         self.current_event = self.state()
║       File "/home/pkim/.pex/install/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl.b99cb007a904e5ca780f7efa316b72252aeb142a/PyYAML-3.12-cp27-cp27mu-linux_x86_64.whl/yaml/parser.py", line 174, in parse_document_start
║         self.peek_token().start_mark)
║     ParserError: expected '<document start>', but found '<block mapping start>'
║       in "/home/pkim/git/net-diagnostics/.forge/k8s/net-diagnostics/forge-template/README.md", line 9, column 1


```

**Comment by rhs** [comment]
This should be fixed in forge 0.4.11
