### ISSUE TITLE
can't run forge setup in katacoda container (forge 0.3.6)

### ISSUE THREAD

**Issue by richarddli** [datawire/forge#69]
`> ~/.bin/forge setup
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 361, in execute
  File ".bootstrap/_pex/pex.py", line 289, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 321, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 404, in _execute
  File ".bootstrap/_pex/pex.py", line 462, in execute_entry
  File ".bootstrap/_pex/pex.py", line 480, in execute_pkg_resources
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/cli.py", line 486, in call_main
    exit(forge())
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/scrapbook/.pex/install/click-6.7-py2.py3-none-any.whl.6d9ff910081ac14222b6215822bc2664662de745/click-6.7-
py2.py3-none-any.whl/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/cli.py", line 378, in setup
    return forge.setup()
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/tasks.py", line 243, in __call__
    return result.get()
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/executor.py", line 400, in do_run
    result.value = fun(*args, **kwargs)
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/cli.py", line 130, in setup
    task.echo(self.terminal.bold("== Checking Kubernetes Setup =="))
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/tasks.py", line 208, in echo
    executor.current().echo(*args, **kwargs)
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/executor.py", line 377, in echo
    print msg
  File "/home/scrapbook/.pex/install/Forge-0.3.6-py2-none-any.whl.491f4e8c18520ad42e6c6460c7040848ac96facc/Forge-0.3.6-
py2-none-any.whl/forge/executor.py", line 215, in write
    self.stream.write(color(u"\u2554\u2550") + color(context) + "\n")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)`

**Comment by plombardi89** [comment]
I believe this can be fixed by setting two environment variables on the host system. I had to do this for Shopbox's docker container:

```
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
```

**Comment by richarddli** [comment]
yes, that fixes the issue
