### ISSUE TITLE
NameError: global name 'Github' is not defined

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#74]
Running on macOS, happens on any release of 0.3.x

Running any `forge build` will trigger this:

```
║   None: unexpected error
║
║     Traceback (most recent call last):
║       File "/Users/tristanpemble/.pex/install/Forge-0.3.10-py2-none-any.whl.e92dbd34aa9cc738765511c6488a36021ae97c22/Forge-0.3.10-py2-none-any.whl/forge/cli.py", line 314, in root
║         for name in self.load_services():
║       File "/Users/tristanpemble/.pex/install/Forge-0.3.10-py2-none-any.whl.e92dbd34aa9cc738765511c6488a36021ae97c22/Forge-0.3.10-py2-none-any.whl/forge/cli.py", line 283, in load_services
║         services.extend(self.discovery.dependencies(services))
║       File "/Users/tristanpemble/.pex/install/Forge-0.3.10-py2-none-any.whl.e92dbd34aa9cc738765511c6488a36021ae97c22/Forge-0.3.10-py2-none-any.whl/forge/service.py", line 154, in dependencies
║         if not self.resolve(svc, r): missing.append(r)
║       File "/Users/tristanpemble/.pex/install/Forge-0.3.10-py2-none-any.whl.e92dbd34aa9cc738765511c6488a36021ae97c22/Forge-0.3.10-py2-none-any.whl/forge/service.py", line 128, in resolve
║         gh = Github(None)
║     NameError: global name 'Github' is not defined
```

**Comment by rhs** [comment]
I was able to reproduce this locally, and I believe it should be fixed now in 0.3.11. Please refile/reopen if this shows up again.
